// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package stats

import (
	"database/sql"
	"time"
)

type Learnable struct {
	Lid      sql.NullString
	Esecs    time.Time
	Timer    time.Duration
	Score    string
	Activity sql.NullString
}

type Tsession struct {
	Esecs      time.Time
	Speed      float64
	Accuracy   float64
	Nquestions int64
}
