// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package stats

import (
	"context"
	"database/sql"
	"time"
)

const createLearnable = `-- name: CreateLearnable :execresult
INSERT INTO learnable (
  lid, esecs, timer, score, activity
) VALUES (
  ?, ?, ?, ?, ?
)
`

type CreateLearnableParams struct {
	Lid      sql.NullString
	Esecs    time.Time
	Timer    time.Duration
	Score    string
	Activity sql.NullString
}

func (q *Queries) CreateLearnable(ctx context.Context, arg CreateLearnableParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLearnable,
		arg.Lid,
		arg.Esecs,
		arg.Timer,
		arg.Score,
		arg.Activity,
	)
}

const deleteLearnable = `-- name: DeleteLearnable :exec
DELETE FROM learnable
WHERE lid = ?
`

func (q *Queries) DeleteLearnable(ctx context.Context, lid sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteLearnable, lid)
	return err
}

const getLearnable = `-- name: GetLearnable :one
SELECT lid, esecs, timer, score, activity FROM learnable
WHERE lid = ? LIMIT 1
`

func (q *Queries) GetLearnable(ctx context.Context, lid sql.NullString) (Learnable, error) {
	row := q.db.QueryRowContext(ctx, getLearnable, lid)
	var i Learnable
	err := row.Scan(
		&i.Lid,
		&i.Esecs,
		&i.Timer,
		&i.Score,
		&i.Activity,
	)
	return i, err
}

const listLearnables = `-- name: ListLearnables :many
SELECT lid, esecs, timer, score, activity FROM learnable
ORDER BY lid
`

func (q *Queries) ListLearnables(ctx context.Context) ([]Learnable, error) {
	rows, err := q.db.QueryContext(ctx, listLearnables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Learnable
	for rows.Next() {
		var i Learnable
		if err := rows.Scan(
			&i.Lid,
			&i.Esecs,
			&i.Timer,
			&i.Score,
			&i.Activity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
